# values.yaml

image:
  repository: volzfr/faaast-service
  tag: cloudtrust
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

fullnameOverride: faaast-service

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - fa3st Service
    nginx.ingress.kubernetes.io/auth-secret: faaast-service-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  tls:
    - hosts:
        - faaast-service.factory-x.catena-x.net
      secretName: tls-secret-faaast-service
  hosts:
    - host: faaast-service.factory-x.catena-x.net
      paths:
        - path: /
          pathType: Prefix
          
basicAuth:
  enabled: true
  secretName: faaast-service-basic-auth
  # pre-generated htpasswd line, e.g. "user1:$apr1$..."
  htpasswd: "berger:$apr1$WQWjvop0$Cqkamc/z5giB9o0/jeZaM1"
  
config:
  mountPath: "/app/config/config.json"

persistence:
  class: "de.fraunhofer.iosb.ilt.faaast.service.persistence.memory.PersistenceInMemory"

messageBus:
  class: "de.fraunhofer.iosb.ilt.faaast.service.messagebus.cloudevents.MessageBusCloudevents"
  host: "wss://mqttbroker.factory-x.catena-x.net:443"
  user: "fx-factory"
  password: "placeholder"

endpoints:
  - class: "de.fraunhofer.iosb.ilt.faaast.service.endpoint.http.HttpEndpoint"
    port: 8080
    corsEnabled: true
    sslEnabled: false

autoscaling:
  enabled: false
serviceAccount:
  # Specifies whether a service account should be created
  create: false
